title: "Richard Costa"
author: "Richard Costa"
description: "Just a personal website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
 #  - {file: "index.md", title: "Home"}
  - {file: "blog.html", title: "Blog"}
  - {file: "index_posts.md", title: "Posts Index"}
  - {file: "index_notes.md", title: "Notes Index"}
  - {file: "art.md", title: "Art"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, url: "mailto:scosta.richard@gmail.com", icon: envelope}
  - {title: Twitter, url: "https://twitter.com/richsicist", icon: twitter}
  - {title: Blog Theme, url: https://github.com/niklasbuschmann/contrast}
 #  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
