---
title: ""
---

# Data Science

## Machine Learning

 - [The word 'tensor' in machine learning, math, and physics](https://stats.stackexchange.com/a/198395)

___
# Math/Physics

## Mathematical Physics

- [nlab entry on mathematical physics](https://ncatlab.org/nlab/show/mathematical+physics).
---
# Linux 

## Arch Linux/Omarchy

Blog posts about Omarchy, an Arch-Linux based distro (or a bunch configurations if you want to call it that way):

- [installing cosmic and changing sddm on omarchy](posts/1.cosmic-and-sddm-omarchy.qmd)
- [installing a calendar widget on omarch](posts/2.calendar-omarchy.qmd)


___
# Other

## Quarto

This site is built using [quarto](https://quarto.org/). To know more about it you should start in the `get started` section. After that, the following articles were particularly useful to me:

- [Creating your personal website using Quarto](https://ucsb-meds.github.io/creating-quarto-websites/#where-you-should-start-changing-stuff)
- [Adding a blog to your existing Quarto website](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/)

My blog posts about quarto:

- [installing quarto on arch linux](posts/3.quarto-arch.md)