from pathlib import Path
import subprocess

REPO_URL = "https://github.com/richard-costa/richard-costa.github.io"


def git(*args: str) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except Exception:
        return ""


raw = git(
    "log",
    "--no-merges",
    "-n",
    "50",
    "--date=short",
    "--pretty=format:%H%x09%ad%x09%s",
)

skip_prefixes = ("automated update", "publish", "merge pull request")
entries = []

for line in raw.splitlines():
    parts = line.split("\t", 2)
    if len(parts) != 3:
        continue
    sha, date, subject = parts
    if subject.lower().startswith(skip_prefixes):
        continue
    entries.append((sha, date, subject))
    if len(entries) >= 12:
        break

lines = []
current_date = None

for sha, date, subject in entries:
    if date != current_date:
        if lines:
            lines.append("")
        lines.extend([f"## {date}", ""])
        current_date = date

    safe_subject = subject.replace("[", "\\[").replace("]", "\\]")
    short = sha[:7]
    lines.append(f"- [{safe_subject}]({REPO_URL}/commit/{sha}) · `{short}`")

if not lines:
    lines.append("_Git history was unavailable for this render._")

output = Path("_generated/changelog.md")
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(
    "<!-- Generated by _scripts/generate_changelog.py -->\n\n"
    + "\n".join(lines)
    + "\n",
    encoding="utf-8",
)
