---
title: 'Review of Quantum Mechanics'
crossref:
    eq-prefix: ""

status: draft # draft | wip | mature
---

This is a review of important concepts in quantum mechanics, aimed at the reader who has already taken a first course on quantum mechanics.

---

### Quantum States

States are represented by vectors in a Hilbert space. A wavefunction $\psi$ is a solution to the Schrödinger equation. It also represents the components of a _state vector_ $\Psi$. If the wavefunction depends on the position $\mathbf{r}$, that is, $\psi = \psi(\mathbf{r})$, then it is a solution to the Schrödinger equation in _position space_ components of $\Psi$ in an infinite dimension along the direction corresponding to a definite value $\mathbf{r}$ of the position. The wavefunction is also a type of _projection_. The state vector $\Psi$ is given by

$$
| \Psi \rangle = \int d^{3} \mathbf{r} | \mathbf{r} \rangle \langle \mathbf{r} | \Psi \rangle
$$ {#eq-state-vector}

and this component in terms of Dirac notation is given by

$$
\langle  \mathbf{r}  | \Psi \rangle = \psi (\mathbf{r}).
$$
Positions are part of a continuous set, so at first: $\mathbf{r} \in [-\infty, \infty ]$. Since each component in the state vector space is associated to a value of the position vector, we have infinite directions in this space and each direction is labeled by $\mathbf{r}$.

The state vector in the form (@eq-state-vector) is just one of the possible representations. In particular, we used the position representation. We can use another system variable such as the momentum. In this case, we have

$$
\langle \mathbf{p} | \Psi \rangle = \phi ( \mathbf{p}),
$$


### Stationary States



### Suggested Reading

 - Weinberg, S., 2015. _Lectures on quantum mechanics_. Cambridge University Press.
 - Merzbacher, E. (1998) _Quantum Mechanics_. John Wiley & Sons.





